#! /bin/sh

killall flashfocus &
polybar top &
sxhkd &
compton &
feh --bg-fill ~/Pictures/1.png &
xinput set-prop 12 306 1 &
xinput set-prop 12 310 1 &
xinput set-prop 12 306 1 &
xinput set-prop 12 314 1 &
xinput set-prop 13 302 1 &
xinput set-prop 13 310 1 &
xinput set-prop 11 302 1 &
xinput set-prop 11 310 1 &
xinput set-prop 12 302 1 &
xinput set-prop 12 310 1 &
setxkbmap pl &
sudo powertop --auto-tune &
sudo rmmod pcspkr &
wmname LG3D &





bspc monitor -d I II III IV V VI VII VIII IX X

bspc config active_border_color \#0000ff
bspc config border_width         1
bspc config window_gap          0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

flashfocus &
